// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CodexSnapshot() {
  return window['go']['main']['App']['CodexSnapshot']();
}

export function ConfigSnapshot() {
  return window['go']['main']['App']['ConfigSnapshot']();
}

export function ConfigureSlack(arg1) {
  return window['go']['main']['App']['ConfigureSlack'](arg1);
}

export function DesktopSnapshot(arg1) {
  return window['go']['main']['App']['DesktopSnapshot'](arg1);
}

export function GUIProbeConfig() {
  return window['go']['main']['App']['GUIProbeConfig']();
}

export function PostSlackProtocol(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostSlackProtocol'](arg1, arg2, arg3);
}

export function ReadinessSnapshot(arg1) {
  return window['go']['main']['App']['ReadinessSnapshot'](arg1);
}

export function RecentMCPRequests(arg1) {
  return window['go']['main']['App']['RecentMCPRequests'](arg1);
}

export function RecentSlackProtocol(arg1, arg2) {
  return window['go']['main']['App']['RecentSlackProtocol'](arg1, arg2);
}

export function ReportFrontendReady(arg1) {
  return window['go']['main']['App']['ReportFrontendReady'](arg1);
}

export function ReportGUIProbe(arg1) {
  return window['go']['main']['App']['ReportGUIProbe'](arg1);
}

export function RequestShutdown() {
  return window['go']['main']['App']['RequestShutdown']();
}

export function RuntimeSnapshot() {
  return window['go']['main']['App']['RuntimeSnapshot']();
}

export function SlackSnapshot() {
  return window['go']['main']['App']['SlackSnapshot']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function UpdatePermissionMode(arg1) {
  return window['go']['main']['App']['UpdatePermissionMode'](arg1);
}
