// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddProject(arg1:app.ProjectCommand):Promise<app.ConfigSnapshot>;

export function CodexSnapshot():Promise<app.CodexSnapshot>;

export function ConfigSnapshot():Promise<app.ConfigSnapshot>;

export function ConfigureSlack(arg1:app.ConfigureSlackCommand):Promise<app.SlackSnapshot>;

export function DesktopSnapshot(arg1:number):Promise<app.DesktopSnapshot>;

export function DiagnosticsSnapshot():Promise<app.DiagnosticsSnapshot>;

export function GUIProbeConfig():Promise<string>;

export function ObservabilitySnapshot():Promise<app.ObservabilitySnapshot>;

export function PostSlackProtocol(arg1:string,arg2:string,arg3:string):Promise<app.SlackMessageSnapshot>;

export function ReadinessSnapshot(arg1:number):Promise<app.ReadinessSnapshot>;

export function RecentMCPRequests(arg1:number):Promise<Array<app.MCPRequestSnapshot>>;

export function RecentSlackProtocol(arg1:string,arg2:number):Promise<Array<app.SlackMessageSnapshot>>;

export function RemoveProject(arg1:string):Promise<app.ConfigSnapshot>;

export function ReportFrontendReady(arg1:string):Promise<void>;

export function ReportGUIProbe(arg1:string):Promise<void>;

export function RequestShutdown():Promise<void>;

export function ResolveDesktopError(arg1:string):Promise<app.ObservabilitySnapshot>;

export function RuntimeSnapshot():Promise<app.RuntimeSnapshot>;

export function SlackSnapshot():Promise<app.SlackSnapshot>;

export function UpdatePermissionMode(arg1:string):Promise<app.ConfigSnapshot>;

export function UpdateProject(arg1:string,arg2:app.ProjectCommand):Promise<app.ConfigSnapshot>;
